osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx

cache:
  directories:
  # 需更新包时注释掉
  - node_modules
  - react/node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_install:
  - npm install
  - cd react
  - npm install

# install:
#   - npm install

script:
  - cd ../
  - npm run dist

branches:
  only:
    - release
    - /^v.*$/

deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  on:
    tags: true
