osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: "mqjMWdFaA37VSbPazvlcOk/eudr/fG42yuJmbxTKrrzWpNxRrvGsUP+yWPM8wFl34kTXr2xKy434DyRDXcbQT7JnVYs9ep+QMPvA6W1Z278fhagxB+DN3yW/2WdZGKEP/htyMhsMnANdY13LsVngDp8/9bEdj5A9O2bwJBkS6AImB5J7Trk1rphIbIkVXoWfec8HMDzh/8tykG0AcE96mr7tX4r/0iF6StFX3JZonC98QlJVllA6hy9vWcPT2021mBP4fVJDOdYHMFXbqVryhhMAniSbp/KMgfzHRM7/HeA9Pil7GVDYRHmzEg6sP0YE5J8PC7fGLliWlBDW2fcx6sflHSHzraFaIPxJ4+Kib1PU1GxySL0Z/AZRrLAhrjd9ZBphAdUpWUO+z9akz1oF/fV2Riu0XTP1QVkKzX/mhOPIIUwq14P5JSEV1GlH8vxyWdZcCXa836N8AKMzluRdcvtPmdIMF1X6Cq4d3nBZjJnj2DLw+l8bFkNqtvaeTWnR8pcp+YbmF/lO6wNwOCVV0B9Rmm/YIvmAxpIVboiWpEq9IKi8wFwXUl7+HFo8VXcgBCUszVD4Lvr/H2mnBQyB0QUMy5lnrD6aUkDNN7n+748Iy8lv18XfuB1Ih7JoW7WYkPsX6pxiwU7hRALSbLfgVK1jkaPSC2QhVRfg0ynhzSE="

os:
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

script:
  - npm run dist

branches:
  only:
    - release
