osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

script:
  - npm run dist

branches:
  only:
    - release
    - /^v.*$/

deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "dist/"
  on:
    tags: true
